### PR TITLE
Fix FunctionContext Check and Polymorphic Type Conversions in Activity Analyzer

### LINKED ISSUE #453: Analyzer Rule DURABLE2001 False Positives
The latest changes to the analyzers with `1.12.0` have introduced some false positives with rule `DURABLE2001` including:

- Flagging missing input on activities that bind to `FunctionContext` for their `ActivityTrigger` when used in Azure Functions:
```csharp
[Function(nameof(GetNumber))]
public async Task<int> GetNumber([ActivityTrigger] FunctionContext context)
{
    // Something ...
}

[Function(nameof(DoMath))]
public async Task DoMath([OrchestrationTrigger] TaskOrchestrationContext context)
{
    // error DURABLE2001: CallActivityAsync is passing the incorrect type 'none' instead of 'FunctionContext' to the activity function 'GetNumber'
    int num = await context.CallActivityAsync<int>(nameof(GetNumber));
    // ... More stuff ...
}
```
- Polymorphism does not seem to be considered properly on input. E.g. a `List<int>` argument is flagged as invalid when passed to an activity that accepts `IReadOnlyList<int>`. I know this can be a bit hairy given the extension's own JSON representation though.
    - Or perhaps all types represented by the same JSON type are acceptable alternatives? E.g. Any .NET BCL collection is a JSON array, so they can be interchanged? Although, that may rely too much on implementation details

```csharp
[Function(nameof(Sum))]
public int Sum([ActivityTrigger] IReadOnlyList<int> numbers)
    => numbers.Sum();

[Function(nameof(DoMath))]
public async Task DoMath([OrchestrationTrigger] TaskOrchestrationContext context)
{
    // error DURABLE2001: CallActivityAsync is passing the incorrect type 'List<int>' instead of 'IReadOnlyList<int>' to the activity function 'Sum'
    List<int> numbers = [1, 2, 3, 4, 5];
    int sum = await context.CallActivityAsync<int>(nameof(Sum), numbers);
    // ... More stuff ...
}
```

### PR DESCRIPTION
**Pull request by nytian**
Fix #453

### CODE REVIEW

File: src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs
Comment (bachuv) [inline src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs:1]: Can you give more examples in the comments for each if statement check of what would make the if statement true? The if statements with comments like the one below were helpful when reading the code.

> // Special handling for collection types since ClassifyConversion doesn't always recognize
        // generic interface implementations (e.g., List<T> to IReadOnlyList<T>)

File: src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs [hunk 1]
```diff
@@ -330,6 +341,133 @@ public override void Initialize(AnalysisContext context)
...
+    static bool AreTypesCompatible(Compilation compilation, ITypeSymbol? sourceType, ITypeSymbol? targetType)
+    {
+        // Both null = compatible
+        if (sourceType == null && targetType == null)
+        {
+            return true;
+        }
+
+        // One is null, the other isn't = not compatible
+        if (sourceType == null || targetType == null)
```
Comment (andystaples) [inline src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs]: Just checking - does this logic support passing null as input to a nullable function parameter? That was also an issue with this analyzer previously

File: src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs [hunk 2]
```diff
@@ -330,6 +345,139 @@ public override void Initialize(AnalysisContext context)
...
+            if (sourceType == null && targetType != null)
+            {
+                // Check if target is a nullable reference type (NullableAnnotation.Annotated)
+                // or a nullable value type (Nullable<T>)
+                if (targetType.NullableAnnotation == NullableAnnotation.Annotated ||
+                    targetType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
+                {
+                    return true;
+                }
+            }
```
[the remark this answers is not in the document]
Comment (nytian) [reply src/Analyzers/Activities/MatchingInputOutputTypeActivityAnalyzer.cs]: turns out this is not right

**Comment by nytian** [comment]
E2E test 
-- with latest v1.11.1
image
--with fix
image
